vich_uploader:
    db_driver: orm

    mappings:
       user_folder:
            uri_prefix: /user
            upload_destination: '%kernel.project_dir%/public/user'
            delete_on_update: false
            delete_on_remove: false
